### ISSUE TITLE
Update an Open Dropdown Menu

### ISSUE THREAD

**Issue by cody1024d** [AhmedLSayed9/dropdown_button2#101]
Right now I'm putting together a hacky solution using the search functionality provided in this framework.

However, overall, I'd like the ability to dynamically update the dropdown menu items on a dropdown that's open.

My use case is as follows:

When the user first taps on the dropdown, we make an async call to get the items. While this call is occurring I show a single item, that represents the loading state. Once these items have been fetched, I'd like to push them into the already open menu.  As of right now, I don't think there's a way to update the state of the DropDownMenu, besides hacking together something with the search controller (which is what I'm going to do)

**Edit**: My hack unfortunately doesn't even work either :( This is because the searchController only goes through the items on the DropDownRoute, which is not updated with the latest items either

**Comment by AhmedLSayed9** [comment]
Sure, give it a try.
I think it's more difficult than that, check `_handleTap()` method.
I think we need `ValueListenableBuilder` to achieve this.

**Comment by AhmedLSayed9** [comment]
This is a hacky solution for now that auto re-open the dropdown menu in milliseconds:

```
  final dropdownKey = GlobalKey<DropdownButton2State>();
  bool _isOpen = false;

  List<String>? items;
  String? selectedValue;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: DropdownButtonHideUnderline(
          child: DropdownButton2(
            key: dropdownKey,
            hint: Text(
              'Select Item',
              style: TextStyle(
                fontSize: 14,
                color: Theme.of(context).hintColor,
              ),
            ),
            onMenuStateChange: (bool isOpen) async {
              _isOpen = isOpen;
              if (isOpen && items == null) {
                //Simulate api call delay to show loading for 3 seconds
                await Future.delayed(const Duration(seconds: 3));
                setState(() {
                  items = [
                    'Item1',
                    'Item2',
                    'Item3',
                    'Item4',
                  ];
                });

                //Return if the user already closed the menu
                if (!_isOpen) return;

                Navigator.of(context).pop();
                //await removeDropdownRoute to avoid _dropdownRoute != null Exception
                await Future.delayed(const Duration(milliseconds: 100));
                dropdownKey.currentState!.callTap();
              }
            },
            items: items == null
                ? [
                    const DropdownMenuItem<String>(
                      enabled: false,
                      child: Center(
                        child: CircularProgressIndicator(),
                      ),
                    ),
                  ]
                : items!
                    .map((item) => DropdownMenuItem<String>(
                          value: item,
                          enabled: false,
                          child: Text(
                            item,
                            style: const TextStyle(
                              fontSize: 14,
                            ),
                          ),
                        ))
                    .toList(),
            value: selectedValue,
            onChanged: (value) {
              setState(() {
                selectedValue = value as String;
              });
            },
            buttonHeight: 40,
            buttonWidth: 140,
          ),
        ),
      ),
    );
  }
```
https://user-images.githubusercontent.com/70890146/202493174-2db2b0ce-f5a7-48a1-8664-8d692c3db20c.mov

**Comment by cody1024d** [comment]
Thank you for that @AhmedLSayed9 .  Unfortunately; I have another wrench to throw into things -- I'm using the DropdownButtonFormField2; and so it's state is not DropDownButton2State, which complicates me calling callTap().

**Comment by AhmedLSayed9** [comment]
You can use [dropdownButtonKey](https://pub.dev/documentation/dropdown_button2/latest/dropdown_button2/DropdownButtonFormField2/dropdownButtonKey.html) property now in v1.9.1
I think a secondary key to access the child is more proper 🙂

**Comment by cody1024d** [comment]
@AhmedLSayed9  v1.9.1 is working based on your solution above, thank you ahmed!

One thing I noticed though, is that I'm seeing the following error in the log (after updating from v1.8.9 -> v1.9.1 [I tried v1.9.0 as well]):

```
The following _CastError was thrown during paint():
Null check operator used on a null value

The relevant error-causing widget was: 
  DropdownButtonFormField2<_DropDownWrapper>-[GlobalKey#07451] DropdownButtonFormField2:file:///Users/Cody/Dev/Work/Verfico/flutter_app/lib/views/themed/themed_dropdown_form_field.dart:65:20
When the exception was thrown, this was the stack: 
#0      RenderIndexedStack.debugDescribeChildren (package:flutter/src/rendering/stack.dart:793:26)
#1      DiagnosticableTreeNode.getChildren (package:flutter/src/foundation/diagnostics.dart:2985:48)
#2      DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1620:32)
#3      DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#4      DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1686:19)
#5      MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#6      ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#7      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#8      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#9      new List.of (dart:core-patch/array_patch.dart:51:28)
#10     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#11     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1687:8)
#12     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1654:23)
#13     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#14     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1686:19)
#15     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#16     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#17     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#18     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#19     new List.of (dart:core-patch/array_patch.dart:51:28)
#20     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#21     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1687:8)
#22     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1654:23)
#23     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#24     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1686:19)
#25     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#26     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#27     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#28     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#29     new List.of (dart:core-patch/array_patch.dart:51:28)
#30     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#31     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1687:8)
#32     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1654:23)
#33     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#34     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1686:19)
#35     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#36     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#37     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#38     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#39     new List.of (dart:core-patch/array_patch.dart:51:28)
#40     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#41     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1687:8)
#42     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1654:23)
#43     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#44     DiagnosticsNode.toJsonList.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1686:19)
#45     MappedListIterable.elementAt (dart:_internal/iterable.dart:413:31)
#46     ListIterator.moveNext (dart:_internal/iterable.dart:342:26)
#47     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:189:27)
#48     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
#49     new List.of (dart:core-patch/array_patch.dart:51:28)
#50     ListIterable.toList (dart:_internal/iterable.dart:213:44)
#51     DiagnosticsNode.toJsonList (package:flutter/src/foundation/diagnostics.dart:1687:8)
#52     DiagnosticsNode.toJsonMap.<anonymous closure> (package:flutter/src/foundation/diagnostics.dart:1648:25)
#53     DiagnosticsNode.toJsonMap (package:flutter/src/foundation/diagnostics.dart:1661:6)
#54     WidgetInspectorService._nodeToJson (package:flutter/src/widgets/widget_inspector.dart:1606:18)
#55     WidgetInspectorService._reportStructuredError (package:flutter/src/widgets/widget_inspector.dart:937:44)
#56     FlutterError.reportError (package:flutter/src/foundation/assertions.dart:1184:14)
#57     RenderObject._debugReportException (package:flutter/src/rendering/object.dart:1519:18)
#58     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2800:7)
#59     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#60     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#61     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#62     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#63     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#64     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#65     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#66     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#67     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#68     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#69     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#70     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#71     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#72     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#73     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#74     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#75     _RenderDecoration.paint.doPaint (package:flutter/src/material/input_decorator.dart:1504:17)
#76     _RenderDecoration.paint (package:flutter/src/material/input_decorator.dart:1559:5)
#77     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#78     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#79     RenderProxyBoxMixin.paint (package:flutter/src/rendering/proxy_box.dart:144:15)
#80     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#81     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#82     RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2900:15)
#83     RenderFlex.paint (package:flutter/src/rendering/flex.dart:1088:7)
#84     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#85     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:239:13)
#86     _RenderSingleChildViewport.paint.paintContents (package:flutter/src/widgets/single_child_scroll_view.dart:562:17)
#87     PaintingContext.pushLayer (package:flutter/src/rendering/object.dart:460:12)
#88     PaintingContext.pushClipRect (package:flutter/src/rendering/object.dart:520:7)
#89     _RenderSingleChildViewport.paint (package:flutter/src/widgets/single_child_scroll_view.dart:566:40)
#90     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2796:7)
#91     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:155:11)
#92     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:98:5)
#93     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:1116:31)
#94     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:515:19)
#95     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:884:13)
#96     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#97     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#98     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#99     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#100    _invoke (dart:ui/hooks.dart:148:13)
#101    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#102    _drawFrame (dart:ui/hooks.dart:115:31)
The following RenderObject was being processed when the exception was fired: RenderPointerListener#8b42c relayoutBoundary=up24
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...  size: Size(363.4, 24.0)
...  behavior: opaque
...  listeners: down, panZoomStart
RenderObject: RenderPointerListener#8b42c relayoutBoundary=up24
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
  size: Size(363.4, 24.0)
  behavior: opaque
  listeners: down, panZoomStart
...  child: RenderConstrainedBox#fd169 relayoutBoundary=up25
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=363.4, 0.0<=h<=Infinity)
...    size: Size(363.4, 24.0)
...    additionalConstraints: BoxConstraints(0.0<=w<=Infinity, h=24.0)
...    child: RenderPadding#a7621
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=363.4, h=24.0)
...      size: Size(363.4, 24.0)
...      padding: EdgeInsets.zero
...      textDirection: ltr
...      child: RenderFlex#4853b OVERFLOWING
...        parentData: offset=Offset(0.0, 0.0) (can use size)
...        constraints: BoxConstraints(w=363.4, h=24.0)
...        size: Size(363.4, 24.0)
...        direction: horizontal
...        mainAxisAlignment: spaceBetween
...        mainAxisSize: min
...        crossAxisAlignment: center
...        textDirection: ltr
...        verticalDirection: down
...        child 1: RenderPadding#6818a relayoutBoundary=up1
...          parentData: offset=Offset(0.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=24.0)
...          size: Size(346.0, 24.0)
...          padding: EdgeInsets(16.0, 0.0, 16.0, 0.0)
...          textDirection: ltr
...        child 2: RenderSemanticsAnnotations#5fdb3 relayoutBoundary=up1
...          parentData: offset=Offset(346.0, 0.0); flex=null; fit=null (can use size)
...          constraints: BoxConstraints(0.0<=w<=Infinity, 0.0<=h<=24.0)
...          size: Size(24.0, 24.0)

```

This wasn't happening in the earlier version I mentioned above; so something may have been changed to cause this? :(

**Comment by AhmedLSayed9** [comment]
I'm unable to release the issue above. Can you provide a working sample that cause it?

**Comment by cody1024d** [comment]
@AhmedLSayed9 This seems to be an issue on my end. I refactored by code, and it's no longer an issue. Sorry about that!.  I'm editing my above comment so no one gets confused
