### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by helloalbin** [AhmedLSayed9/dropdown_button2#39]
Getting the following error in iOS simulator. 

```
flutter: Null check operator used on a null value
flutter: 
#0      DropdownButton2State.didChangeMetrics (package:dropdown_button2/dropdown_button2.dart:1544:20)
#1      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:570:16)
#2      _rootRun (dart:async/zone.dart:1426:13)
#3      _CustomZone.run (dart:async/zone.dart:1328:19)
#4      _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
#5      _invoke (dart:ui/hooks.dart:151:10)
#6      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:236:5)
#7      _updateWindowMetrics (dart:ui/hooks.dart:33:31)
```

**Comment by AhmedLSayed9** [comment]
Can you please provide flutter doctor summary and a sample of the code?

**Comment by Colton127** [comment]
I'm getting the same issue in my project after the latest update.

**Comment by AhmedLSayed9** [comment]
The issue is related to https://github.com/flutter/flutter/issues/89824. It happens because didChangeMetrics() on iOS is getting called when app starts but it should only be called when metrics change.

I'll fix it, Thanks guys.
