### ISSUE TITLE
Scrollbar Assertion Failed on clicking dropdown

### ISSUE THREAD

**Issue by SpongeManiac** [AhmedLSayed9/dropdown_button2#49]
This error appears in my output every time I click on a drop down from this library. There isn't anything fancy on my drop down. This happens on Windows and Web. The error itself does not affect the functioning of the drop down, however it is quite annoying to see it every time I click something. If there is a way to silence it or to solve the problem, please let me know.

Here is my build function:
```
Widget build(BuildContext context) {
    return ValueListenableBuilder(
      valueListenable: globals.app.homePageStateNotifier,
      builder: (context, HomePageData newState, _) {
        newState.saveData();
        loadState(newState);
        return Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              const Text(
                'You have pushed the button this many times:',
              ),
              Text(
                '$_counter',
                style: Theme.of(context).textTheme.headline4,
              ),
              DropdownButtonHideUnderline(
                child: DropdownButton2(
                  items: _themeDropdown,
                  value: _selectedItem,
                  onChanged: (MaterialColor? newval) {
                    _themeChanged(newval);
                  },
                  isExpanded: true,
                  buttonDecoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                    border: Border.all(
                      color: Colors.grey,
                    ),
                  ),
                  dropdownDecoration: BoxDecoration(
                    borderRadius: BorderRadius.circular(15),
                    border: Border.all(
                      color: Colors.grey,
                    ),
                  ),
                  buttonWidth: 300,
                ),
              ),
            ],
          ),
        );
      },
    );
  }
```

Here is the output for Windows & Web:

Windows (Desktop)
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 151 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      ScrollController.animateTo (package:flutter/src/widgets/scroll_controller.dart:151:12)
#3      _DropdownMenuItemButtonState._handleFocusChange (package:dropdown_button2/dropdown_button2.dart:144:38)
#4      _InkResponseState.handleFocusUpdate (package:flutter/src/material/ink_well.dart:1028:27)
#5      _FocusState._handleFocusChanged (package:flutter/src/widgets/focus_scope.dart:632:27)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:351:24)
#7      FocusNode._notify (package:flutter/src/widgets/focus_manager.dart:1038:5)
#8      FocusManager._applyFocusChange (package:flutter/src/widgets/focus_manager.dart:1804:12)
#9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

Web (Chrome)
```
Error: Assertion failed: file:///D:/GitHub/flutter/packages/flutter/lib/src/widgets/scroll_controller.dart:151:12
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
266:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart
29:3    assertFailed
packages/flutter/src/widgets/scroll_controller.dart 151:23
animateTo
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54
runBody
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:5
_async
packages/flutter/src/widgets/scroll_controller.dart 146:25
animateTo
packages/dropdown_button2/dropdown_button2.dart 144:20
[_handleFocusChange]
packages/flutter/src/material/ink_well.dart 1028:27
handleFocusUpdate
packages/flutter/src/widgets/focus_scope.dart 632:27
[_handleFocusChanged]
packages/flutter/src/foundation/change_notifier.dart 351:24
notifyListeners
packages/flutter/src/widgets/focus_manager.dart 1038:5
[_notify]
packages/flutter/src/widgets/focus_manager.dart 1804:11
[_applyFocusChange]
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 40:11
_microtaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/async/schedule_microtask.dart 49:5
_startMicrotaskLoop
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 166:15
<fn>
```

**Comment by AhmedLSayed9** [comment]
I've tried to produce the issue with Web (Chrome) but I couldn't. Your sample miss some parameters/functions so I couldn't fully tested it. Can you test the below sample and check if you still get the issue? If not, Please provide a full sample code.

```
final List<String> items = [
    'Item1',
    'Item2',
    'Item3',
    'Item4',
    'Item5',
    'Item6',
    'Item7',
    'Item8',
  ];
  String? selectedValue;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text(
              'You have pushed the button this many times:',
            ),
            Text(
              'counter',
              style: Theme.of(context).textTheme.headline4,
            ),
            DropdownButtonHideUnderline(
              child: DropdownButton2(
                items: items
                    .map((item) => DropdownMenuItem<String>(
                          value: item,
                          child: Text(
                            item,
                            style: const TextStyle(
                              fontSize: 14,
                            ),
                          ),
                        ))
                    .toList(),
                value: selectedValue,
                onChanged: (value) {
                  setState(() {
                    selectedValue = value as String;
                  });
                },
                isExpanded: true,
                buttonDecoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(15),
                  border: Border.all(
                    color: Colors.grey,
                  ),
                ),
                dropdownDecoration: BoxDecoration(
                  borderRadius: BorderRadius.circular(15),
                  border: Border.all(
                    color: Colors.grey,
                  ),
                ),
                buttonWidth: 300,
              ),
            ),
          ],
        ),
      ),
    );
  }
```

**Comment by AhmedLSayed9** [comment]
I'm closing this till new updates of the issue.
